### ISSUE TITLE
Crash when opening emulator with partition key

### ISSUE THREAD

**Issue by oduis** [sachabruttin/CosmosDbExplorer#20]
I have a collection with a partion key to a JSON sub node (/node1/node2/node3), configured in the local CosmosDB emulator.
When trying to open the documents I get errors that the "Identifier <nodename> could not be resolved.
Works nicely in the built in emulator web explorer.

**Comment by sachabruttin** [comment]
Fixed on #21 release v0.7.1-beta

**Comment by oduis** [comment]
Thank you very much for fixing this so quickly! I just tested it, works like a charm.
