### ISSUE TITLE
Release downloads not working

### ISSUE THREAD

**Issue by erizzo** [sachabruttin/CosmosDbExplorer#27]
The ZIP download links for releases are not working. They seem to be pointing to an AWS server that doesn't exist:

github-production-release-asset-2e65be.s3.amazonaws.com’s server IP address could not be found.

**Comment by sachabruttin** [comment]
Looks like a GitHub temporary issue. I cannot reproduce it.

**Comment by jbrepogmailcom** [comment]
I had this problem with other products releases. It seems to be problem with my router that was not able to resolve IP address. Download to mobile phone worked fine (wifi router bypassed)
