### ISSUE TITLE
Cross Partition Query. Null Reference Exception

### ISSUE THREAD

**Issue by ilson-** [sachabruttin/CosmosDbExplorer#45]
Hi!
Doesn't work for query:
SELECT TOP 20 * FROM c
WHERE  c.Key = 'audit_log_2017_d8eeaa90-0348-4a7d-bf9e-3ecb32172640' OR  c.Key = 'audit_log_2018_d8eeaa90-0348-4a7d-bf9e-3ecb32172640'

But it works for:
SELECT TOP 20 * FROM c
WHERE  c.Key = 'audit_log_2017_d8eeaa90-0348-4a7d-bf9e-3ecb32172640'
![image](https://user-images.githubusercontent.com/5246985/100064945-37938280-2e44-11eb-9998-a107d1b52247.png)

**Comment by sachabruttin** [comment]
Sorry, I cannot reproduce this issue on my side. Can you provide a an access to a test db where your encounter this issue?

**Comment by ilson-** [comment]
I think it might be because of TOP keyword. For example in my local db.
Without TOP 3
![image](https://user-images.githubusercontent.com/5246985/100519009-3e085e00-31a6-11eb-9d0a-b43fd21381a7.png)

With TOP 3
![image](https://user-images.githubusercontent.com/5246985/100519030-61330d80-31a6-11eb-955d-28f6a2a63ba7.png)

Raw Data
[
  {
    "id": "1",
    "Key": 2019,
    "Name": "Vasya"
  },
  {
    "id": "2",
    "Key": 2020,
    "Name": "Maria"
  },
  {
    "id": "3",
    "Key": 2021,
    "Name": "Hillary"
  }
]
