### ISSUE TITLE
StringToNumber is not a recognized built-in function name

### ISSUE THREAD

**Issue by houstonhaynes** [sachabruttin/CosmosDbExplorer#49]
StringToFunction works as expected in the Cosmos DB Emulator web console when querying but causes an error in Cosmos DB Explorer. I suppose it's an out-of-date Core component?

![image](https://user-images.githubusercontent.com/8174976/101121876-00d90d00-35a6-11eb-8513-dd6682b3cc51.png)

**Comment by sachabruttin** [comment]
Fixed in release 0.8.0.0
