### ISSUE TITLE
Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by JustinFeistner** [sachabruttin/CosmosDbExplorer#57]
A new version of Cosmos DB Explorer came out and the update won't finish and this message keeps popping up every couple minutes. File will not download

![image](https://user-images.githubusercontent.com/45182444/116718435-91721880-a99f-11eb-8ef7-3dafd5f03fb3.png)

**Comment by sachabruttin** [comment]
Fixed in release 0.8.3
