### ISSUE TITLE
support for full SELECT window

### ISSUE THREAD

**Issue by katlimruiz** [sachabruttin/CosmosDbExplorer#59]
It would be great if you open the filter to the whole select statement.

Right now it can only do SELECT * FROM

while for some big objects, is better to return only a few fields, or to be able to test some transformations.

Azure Storage Explorer already has that, so I guess that is a benchmark to follow (since ASE will deprecate cosmos in the future, and this tool which seems great seems to be the alternative).

**Comment by sachabruttin** [comment]
You can use the "SQL Query" window for that. Just right-click on the collection name.
