### ISSUE TITLE
Add to Scoop catalog

### ISSUE THREAD

**Issue by aloneguid** [sachabruttin/CosmosDbExplorer#69]
Would be great to have this installable via [scoop.sh](https://scoop.sh/). I don't mind doing it if you are OK with this?

**Comment by sachabruttin** [comment]
Could be great. Let's do it.

**Comment by aloneguid** [comment]
Done. It can be installed with `scoop install cosmosdbexplorer-beta` and is in the `versions` bucket.

**Comment by sachabruttin** [comment]
Thanks, what is the process when a new version is released?

**Comment by aloneguid** [comment]
They check github releases page automatically and update the manifest.
