### ISSUE TITLE
FoldManager unable to fold on square brackets

### ISSUE THREAD

**Issue by Curlack** [sachabruttin/CosmosDbExplorer#76]
I love this utility and wondered if I would be able to add array folding to the current curly brace folding. It makes it easier to manage large list inside documents. While tinkering, I also saw CPU usage increase (to 25% on my machine) the moment the folding timer kicked in and it never comes down. Not even if I close the open tabs.

I was able to fix these issues using Regex and OnTextChange event for the folding. Can create a PR if you like. Bear in mind I haven't done a PR before.

Regards

**Comment by sachabruttin** [comment]
Hi @Curlack, yes please create a PR. I'll we be happy to fix this issue.
