### ISSUE TITLE
Encrypt connection string when entered, with * characters

### ISSUE THREAD

**Issue by rubenCumbreno** [sachabruttin/CosmosDbExplorer#98]
Hi, If possible, we would need the tool to encrypt or the possibility of encrypting with * the connection string when it is entered manually, so that it is not visible. Thank you so much.

**Comment by cmendible** [comment]
Possible solution: use a `PasswordBox `instead of a `TextBox `in `AccountSettings.xaml` and for bindings to work an attached property should be implemented.

**Comment by sachabruttin** [comment]
Work in progress on the branch https://github.com/sachabruttin/CosmosDbExplorer/tree/98-encrypt-connection-string-when-entered-with-characters
